from nltk.tokenize import word_tokenize
from nltk.util import ngrams
from professors import db
from flask import request,jsonify
from flask_restx import Resource
from professors import api

from professors.models.funding import *



# If you haven't downloaded the punkt tokenizer, do so first
# nltk.download('punkt')

class Get_funding_analysis_keywords(Resource):
    @api.doc(responses={200: 'OK', 404: 'Not Found', 500: 'Internal Server Error'})

    def get(self, funding_id):

        try:
            #get funding requirement details of the funding
            funding_details = FundingModel.query.filter_by(id=funding_id).all()
            funding_details = funding_details[0]
            funding_keywords = extract_keywords(funding_details.requirement_description, cs_terms)
            # print(funding_keywords)


            
            return jsonify(funding_keywords)
        except Exception as e:
            print({"message":"exception occured in get_funding_analysis_keywods"})
            print(e)
            return jsonify({"message":"exception occured in get_funding_analysis_keywods"})


def extract_keywords(text, cs_terms):
    # Tokenize the text
    tokens = word_tokenize(text.lower())

    # Find both one-word and two-word phrases
    one_word_phrases = tokens
    two_word_phrases = [' '.join(gram) for gram in ngrams(tokens, 2)]

    # Combine the one-word and two-word phrases
    all_phrases = one_word_phrases + two_word_phrases

    # Filter out the phrases based on the computer science terms list (case-insensitive)
    keywords = [phrase for phrase in all_phrases if phrase.lower() in cs_terms]

    # Make the list unique
    keywords = list(set(keywords))

    return keywords


# A predefined list of computer science terms (this can be expanded)
# cs_terms = {
#     "artificial intelligence", "image recognition","neural networks", "optimization", "logistics", 
#     "transportation", "finance", "engineering", "machine learning", "data mining", 
#     "deep learning", "natural language processing", "algorithm", "computational", 
#     "database", "security", "cryptography", "software engineering", "computer graphics", 
#     "quantum computing", "distributed systems", "bioinformatics", "robotics", "computer vision",
#     "computer architecture", "operating systems", "computer networks", "human-computer interaction",
#     "computer science", "computer", "science", "computing", "computers", "software", "hardware, Error Analysis, Speech Recognition, Signal Processing, Phonetics"
# }

cs_terms = {
        "Learning (artificial intelligence)",
        "Fault tolerance",
        "neural network",
        "Tomography",
        "permission check",
        "Unconditional derandomization",
        "Matroids",
        "Logistics",
        "Power transformer insulation",
        "Arts/games/social media",
        "diversification",
        "Generalization in Reinforcement Learning",
        "body",
        "Model checking",
        "Semantics preserving transformations",
        "software libraries",
        "Deep learning architectures and techniques; Computational photography; Machine learning",
        "exploration",
        "Spatiotemporal Generative Adversarial Network-Based Dynamic Texture Synthesis for Surveillance Video Coding",
        "Heart beat",
        "social media analytics",
        "health sensing",
        "Machine vision",
        "Intelligent transportation systems",
        "granger causality",
        "Transducers",
        "emotion",
        "Seismic measurements",
        "back-propagation neural network",
        "Support vector machines",
        "Walsh code",
        "Art",
        "compiler",
        "Data Visualization",
        "Monitoring",
        "Cold boot attack",
        "Computer security",
        "Junctions",
        "cloth mechanics",
        "noninvasive",
        "Integrated circuit modeling",
        "Learning for Soft Robots",
        "Internet-of-Things (IoT)",
        "mode collapse",
        "Minimization",
        "Germanium",
        "Application",
        "Storage automation",
        "Passive RFID tags",
        "Reactive power",
        "Interactive systems",
        "Lyapunov functions",
        "anonymous sequential games",
        "MRI connectivity",
        "heavy hitters",
        "3D from multi-view and sensors",
        "Four-wave mixing",
        "Ballistocardiograms",
        "Photography",
        "Combinatorial Optimization",
        "Extraterrestrial measurements",
        "particle swarm optimization algorithm",
        "Autoencoder",
        "Resistance heating",
        "Vehicle routing",
        "autonomous vehicle navigation",
        "Pattern analysis",
        "Image and video manipulation detection and integrity methods",
        "endurance",
        "peel",
        "Programming Abstractions",
        "Trajectory optimization",
        "Perturbation methods",
        "Injection molding",
        "Force",
        "Sugar",
        "Computer worms",
        "wake-up radios",
        "2016 European Modelling Symposium (EMS)",
        "Earth",
        "Systematics",
        "Libraries",
        "scent",
        "Blacklisting",
        "COVID-19 vaccine",
        "Deep learning in grasping and manipulation",
        "Stack Overflow",
        "Photovoltaic cells",
        "Optimization",
        "CBRAM",
        "Telemedicine",
        "Algorithms",
        "Payloads",
        "Fuses",
        "Maximum likelihood decoding",
        "packaged array",
        "Scattering",
        "Representation Learning",
        "Resistance",
        "Map-Reduce",
        "Wildlife",
        "Switched mode power supplies",
        "Kinematics",
        "Accessibility",
        "multi-modal data",
        "global image features",
        "natural language processing (NLP)",
        "minimum cut",
        "Algorithm design and analysis",
        "cloud computing security",
        "Strict saddle problem",
        "Transfer/Low-shot/Semi/Unsupervised Learning",
        "Snake robots",
        "visual",
        "semi-automated tracking",
        "Prototypes",
        "CNN",
        "Video games",
        "multi-player games",
        "microchips",
        "circadian rhythm",
        "Crystals",
        "Multiple Object Tracking",
        "Dielectrics",
        "Memory",
        "transparency",
        "Action recognition",
        "intelligent fault diagnosis",
        "Doppler",
        "integratedduplexer",
        "kTails",
        "near-data-processing",
        "density estimation",
        "hybrid-transactional/analytical-processing-(HTAP)",
        "self-driving cars",
        "spectral sparsification",
        "transshipment",
        "Graphene",
        "Wearable computers",
        "low-precision training",
        "stylegan",
        "CNF satisfiability",
        "Comprehension",
        "Timbre",
        "design",
        "Latent engagement models",
        "Brain modeling",
        "Learning from Demonstration",
        "Artifacts",
        "quantum computing",
        "energy harvesting",
        "Detectors",
        "Field programmable gate arrays",
        "Task analysis",
        "Lakes",
        "Servosystems",
        "Earthquakes",
        "analog-to-digital converter (ADC)",
        "Streaming media",
        "Parameter estimation",
        "human-computer interaction",
        "Scheduling algorithm",
        "Connected vehicles",
        "Distributed Stratified Online Sampling",
        "immersion",
        "Optimization and optimal control",
        "final project",
        "Adversarial attack and defense",
        "Affective visualization",
        "trigger circuits",
        "Computational geometry",
        "Version Management",
        "Interviews",
        "optimal mechanism design",
        "Termination of employment",
        "SiC MOSFET",
        "anonymous network",
        "Usability",
        "deterministic approximate counting",
        "Sparse matrices",
        "reconfiguration of cell and pack connections",
        "Clocks",
        "Foot",
        "shapes",
        "Failure analysis",
        "Alzheimer Disease",
        "Adversarial robustness",
        "Recognition: Detection",
        "Presence Sensing",
        "CDN",
        "Circuit optimization",
        "Resonator filters",
        "Pathology",
        "wake-up receivers (WuRXs)",
        "Iron",
        "security verification",
        "Social network services",
        "FPGAs",
        "Information diffusion",
        "Medical diagnostic imaging",
        "(050.4865) Optical vortices",
        "Interpretability",
        "MIMO",
        "Rollover",
        "Computer vision",
        "Chirp",
        "Tensile stress",
        "Table lookup",
        "Atomic measurements",
        "Schools",
        "synoptic",
        "Generative adversarial network",
        "Encoder-decoder",
        "Supervised learning",
        "field programmable gate arrays",
        "Gender issues",
        "knowledge distillation",
        "Source Separation",
        "autoencoders",
        "Submodular Optimization",
        "humanoid and bipedal locomotion",
        "Publishing",
        "inference comparison",
        "wearable monitoring",
        "Open source software",
        "Image Classification",
        "Fréchet Distance",
        "Self-& semi-& meta- Representation learning",
        "Pain",
        "Twitter",
        "cloud storage",
        "key rollover",
        "Adaptive control",
        "sensing",
        "empirical study",
        "Botnet",
        "Overlay networks",
        "design workshop",
        "Vehicle-to-grid",
        "Patching",
        "Vision + language; Representation learning; Video analysis and understanding; Visual reasoning",
        "range improvement",
        "Chapters",
        "Visualization",
        "Cognitive science",
        "Bandwidth",
        "Pediatrics",
        "DNN acceleration",
        "Electric Vehicle",
        "Steiner trees",
        "Optical pumping",
        "Attack Provenance",
        "crops",
        "Image resolution",
        "Image and video synthesis",
        "Atrophy",
        "Industrial training",
        "Online Algorithm",
        "dual active bridge",
        "Eulerian graphs",
        "Force sensors",
        "Optical filters",
        "Electronic learning",
        "Distributed algorithms",
        "Androids",
        "Computer systems organization-Neural networks",
        "connected and autonomous vehicles",
        "named entity recognition",
        "Collision Avoidance",
        "Flexible printed circuits",
        "toolkit",
        "Distance measurement",
        "Pandemics",
        "Holography",
        "Vision Transformer",
        "Statistical Learning",
        "Neuromorphics",
        "data publishing",
        "Optimal control",
        "CLUSTERGEN",
        "Adaptive clock",
        "Systolic Array",
        "lower bounds",
        "Remanence",
        "logistic regression",
        "LHC environment",
        "Resource management",
        "emerging technologies",
        "Films",
        "literate computing",
        "Computational complexity",
        "Far Field",
        "time-of-flight cameras",
        "Memory disclosure",
        "iterative decoder architecture",
        "malware",
        "reinforcement learning",
        "Maximum a posteriori estimation",
        "hypothesis testing",
        "subgraph matching.",
        "Reliability engineering",
        "cryptography",
        "Resilience",
        "Appraisal",
        "Manufacturing processes",
        "Vmin",
        "Biomedical imaging",
        "water",
        "recurrent neural networks",
        "low-power computing",
        "Functional encryption",
        "Stochastic games",
        "healthcare",
        "Phase locked loops",
        "belief propagation",
        "Abstract Syntax Tree",
        "convolutional neural network",
        "Microscopy",
        "multimodal",
        "inference accelerator",
        "lower bound",
        "Magnetic Sensors",
        "dynamic analysis",
        "content variant generation",
        "Polar codes",
        "context",
        "COVID-19",
        "Bridge circuits",
        "inverse Laplace transform",
        "Biological system modeling",
        "Pins",
        "Brushes",
        "Uncertainty",
        "Transfer",
        "computational geometry",
        "sets",
        "de-identification",
        "Computer aided manufacturing",
        "quality of life technologies",
        "respiration rate",
        "Network",
        "Companies",
        "Generators",
        "Olfactory",
        "Concrete",
        "low-power wireless",
        "Security",
        "joint embedding",
        "Labeling",
        "Hair",
        "Formal Methods",
        "Particle measurements",
        "sparse neural network",
        "integrated voltage regulator",
        "Program-Synthesis",
        "Long Term Evolution",
        "social network analysis",
        "Touch",
        "Heterogeneous Features",
        "Modeling",
        "Manganese",
        "DNS",
        "Solids",
        "Unsupervised learning",
        "blind users",
        "Image reconstruction",
        "Merging",
        "Eye Tracking",
        "legged robots",
        "inheritance",
        "Insertion loss",
        "Climbing robots",
        "person detection",
        "Combinatorial mathematics",
        "Machine Learning",
        "Adversarial examples",
        "Markov processes",
        "frequency division duplex (FDD)",
        "Local area networks",
        "Recognition and classification",
        "Multivariate general linear models",
        "Web and internet services",
        "Wideband",
        "MODIS",
        "tutoring systems",
        "Chemistry",
        "frame rate adaption",
        "Stress testing",
        "Carbon",
        "Array Design",
        "property testing",
        "Optical resonators",
        "in-band FD",
        "Matrix decomposition",
        "Coverage",
        "Ellipsoids",
        "error correction",
        "Extended reality",
        "RNN",
        "Forensics",
        "Calibration",
        "Hardware Transactional Memory",
        "nanotechnology",
        "Representation learning",
        "adhesion",
        "facebook ads",
        "Human-Robot Collaboration",
        "Speech recognition",
        "Geometry",
        "Costs",
        "hate",
        "Principal component analysis",
        "Black localization",
        "video prediction",
        "Resource description framework",
        "Source coding",
        "food tracking",
        "screen-printing",
        "cybersecurity",
        "Mental Recall",
        "delamination",
        "joint language vision",
        "Random variables",
        "GPS",
        "immersive analytics",
        "attention guided scaling",
        "Microprocessors",
        "multi-agent",
        "Integrated circuit interconnections",
        "Histograms",
        "accountability",
        "audio-visual speech recognition",
        "Network diffusion",
        "Energy storage",
        "Formal methods in robotics and automation",
        "Flickr",
        "Agile hardware design",
        "Blindness",
        "Ising models",
        "Manuals",
        "Image databases",
        "Robot vision systems",
        "Computer aided instruction",
        "Information Theory",
        "shortest paths",
        "Low-level and physics-based vision",
        "assistive technologies",
        "Law enforcement",
        "switched-capacitorpower amplifier (SCPA)",
        "multi-modal learning",
        "transformer",
        "big data",
        "Human-robot interaction",
        "input matching",
        "Deep learning methods",
        "Trajectory",
        "Additives",
        "Pulse measurements",
        "Cloth appearance",
        "Soft sensors",
        "Satellites",
        "and algorithms (including transfer)",
        "Optical fiber networks",
        "Program transformation",
        "Compressed sensing",
        "Voltage",
        "university-based phishing campaigns",
        "Heat engines",
        "Human-centered computing—Human computer interaction (HCI)—Interaction paradigms—Virtual reality",
        "Probabilistic-Analysis",
        "Tracking",
        "Neuroimaging",
        "Low-power wide area networks",
        "Stochastic Processes",
        "deletion channel",
        "redundancy",
        "Power demand",
        "support vector regression",
        "machine learning",
        "gaze estimation",
        "Access control",
        "Biology",
        "Friction",
        "Gradient methods",
        "Deformable objects",
        "Markov chains",
        "Show More",
        "Active measurements",
        "(060.2605) Free-space optical communications",
        "Social networking (online)",
        "InvariMint",
        "CSMA wireless networks",
        "low power computer architecture",
        "Dynamics",
        "interaction",
        "hardware defense",
        "Context awareness",
        "Wind forecasting",
        "physical-attack",
        "deep learning in robotics and automation",
        "Grippers",
        "cybercrime",
        "linear systems",
        "Motion pictures",
        "RGB-D Perception",
        "Precision medicine",
        "Drones",
        "BERT",
        "qualitative evaluation",
        "(230.3120) Integrated optics devices",
        "Reachability analysis",
        "Ultrasonic transmitting transducer",
        "Pose estimation",
        "lifetime management",
        "Load modeling",
        "Browsers",
        "power monitoring",
        "maximum flow",
        "programming education",
        "Vehicle to Grid (V2G)",
        "Information filters",
        "feature collection and distribution",
        "Ash",
        "Optimization and Optimal Control",
        "data exploration",
        "Intrusion Detection",
        "Wireless fidelity",
        "Python-Malware",
        "Error floors",
        "DFT",
        "Interference",
        "Nanoscale devices",
        "movement",
        "wideband transmitter (TX)",
        "point cloud",
        "Point cloud compression",
        "postdoc problem",
        "nearest neighbor",
        "Multi-valued attributes",
        "Motion Blur",
        "Damping",
        "Instruments",
        "Models",
        "log quality",
        "Noise reduction",
        "Live Migration",
        "model pruning",
        "Electric breakdown",
        "Shortcut Learning",
        "computer vision for transportation",
        "online algorithms",
        "categorization",
        "Viterbi algorithm",
        "replicated execution",
        "ROC Curve",
        "Screen-camera communication",
        "finger flexion",
        "streaming algorithms",
        "Atmospheric gas plasmas",
        "Reservoirs",
        "Au nano biconical",
        "Search problems",
        "Published: 2019",
        "Robots",
        "Meta-Learning",
        "Vision + Language",
        "Graphics",
        "Voltage control",
        "Output feedback",
        "Elasticity",
        "shared bicycle",
        "Computer crime",
        "Mobile handsets",
        "Path planning",
        "Scheduling",
        "key management",
        "principal component analysis",
        "Trojan Detection",
        "ultrasonic",
        "AI 10 to watch",
        "Robust control",
        "gesture",
        "Space exploration",
        "Human power harvesting",
        "Linux kernel",
        "cutting edge",
        "Limiting",
        "social networks",
        "Smart phones",
        "multi-input multi-output (MIMO)",
        "Laboratories",
        "security",
        "Vibrations",
        "Bidirectional control",
        "Sensitivity and Specificity",
        "Antennas",
        "Perception for grasping and manipulation",
        "Binary analysis",
        "idle listening",
        "Image Processing",
        "disease classification",
        "noninterleaved",
        "sentiment analysis",
        "Portable computers",
        "Psychological",
        "Motion and tracking; Datasets and evaluation",
        "AI Accelerator",
        "Clustering algorithms",
        "at-risk",
        "message-passing decoding",
        "Crosstalk",
        "Urban Environment",
        "multi-aspect sentiment analysis",
        "FFT",
        "Temperature measurement",
        "voltage dithering",
        "Code-domain",
        "semantic matching",
        "cognitive efficiency",
        "Pulse width modulation",
        "error-correcting codes (ECC)",
        "Seminars",
        "pretrained models",
        "Statistics",
        "Graphics processing unit",
        "TCP throughput prediction",
        "multirobot systems",
        "Isoperimetry",
        "Deep Learning",
        "Imaging",
        "vectorization",
        "Radio transmitters",
        "crowdsourcing",
        "Style transfer",
        "Communication",
        "RRAM",
        "Action and Behavior Recognition Biometrics -> Human Motion Analysis/Capture",
        "automatic speech recognition",
        "Wavelength measurement",
        "Artificial intelligence",
        "Extremities",
        "Timing Closure",
        "single-sideband (SSB)",
        "Epilepsy",
        "active processing",
        "fault detection",
        "Level set",
        "Graph neural networks",
        "Refining",
        "Simultaneous localization and mapping",
        "Legged locomotion",
        "Inverse problems",
        "Computers",
        "sound source separation",
        "Robot sensing systems",
        "baseband beamforming",
        "Stars",
        "Bit error rate",
        "Data analysis",
        "Video compression",
        "Capacitor",
        "Probability density function",
        "efficient networks",
        "game theory",
        "person tracking",
        "Quality assessment",
        "mood tracking",
        "Large Hadron Collider",
        "real-time acceleration",
        "ℓp-sampling",
        "neural arch search",
        "yoga",
        "Vision for robotics and autonomous vehicles",
        "adversarial defense",
        "topological persistence",
        "Bellows",
        "Technological innovation",
        "Correlation",
        "Recognition: Categorization",
        "Two dimensional displays",
        "Scene analysis and understanding",
        "Forecasting",
        "sterilization",
        "Distribution functions",
        "Clinical trials",
        "data stream",
        "Communication systems",
        "Kidney",
        "motion",
        "Cloud Computing",
        "Wavelet domain",
        "Equations",
        "phonology",
        "Printing",
        "intelligent systems",
        "Operating systems",
        "Proposals",
        "scene modeling",
        "personal informatics",
        "intelligent and flexible manufacturing",
        "Doppler effect",
        "URE",
        "Nanoparticles",
        "obfuscation",
        "Medical services",
        "History",
        "Deep learning architectures and techniques",
        "Stacking",
        "Heart rate variability",
        "polar transmitter",
        "unwritten languages",
        "Directed minimum cut",
        "systems-security",
        "Graphical overlays",
        "graph comprehension",
        "Topology",
        "Deep Learning for Visual Perception",
        "Convolution",
        "mobile apps",
        "Smoothing methods",
        "Others",
        "Robot motion",
        "energy-efficient processor",
        "self-interferencecancellation",
        "packet detection",
        "Unary computing",
        "Lasers",
        "Clouds",
        "Support vector machine classification",
        "One-shot learning",
        "surface topography",
        "Thickness measurement",
        "censors",
        "Electronic mail",
        "specification mining",
        "Codecs",
        "visual knowledge base",
        "electronicsubtraction",
        "PGD",
        "biomedical retrieval",
        "vae",
        "virtualization",
        "Wildlife recognition",
        "Video recording",
        "machine translation",
        "Intelligent sensors",
        "collectible card game",
        "Riemannian manifold",
        "mean-field games",
        "GPRS",
        "Games",
        "Impedance matching",
        "Microsoft Windows",
        "trace reconstruction",
        "regulation",
        "direct synthesis",
        "Machine learning; Deep learning architectures and techniques; Others",
        "Interception Attacks",
        "Gallium nitride",
        "Meteorology",
        "Graph mining",
        "Parallel processing",
        "depth hierarchy theorem",
        "expander graphs",
        "learning on point clouds",
        "Boolean function",
        "Datasets and evaluation; 3D from multi-view and sensors; Machine learning; Navigation and autonomous driving; Pose estimation and tracking; Scene analysis and understanding; Vision applications and systems",
        "telesurgical robotics",
        "distribution testing",
        "Task Performance and Analysis",
        "Software algorithms",
        "minimax optimization",
        "Upper bound",
        "learning and adaptive systems",
        "In-Memory Computing",
        "Laser theory",
        "Backscatter communications",
        "Linear regression",
        "Encryption",
        "Virtual environments",
        "vector modulator (VM)",
        "sound perception",
        "Biochemistry",
        "linear regression",
        "Skin",
        "Perturbation",
        "Nanocrystalline Core",
        "Digital TV",
        "Navigation and autonomous driving; Motion and tracking",
        "DNNs",
        "phase noise cancellation",
        "Encoding",
        "Lenses",
        "sample complexity",
        "Power system reliability",
        "Transportation",
        "privacy",
        "Unsolicited e-mail",
        "3D object detection",
        "Information security",
        "Katz-Centrality",
        "Persistent Memory",
        "streaming",
        "large text archives",
        "Object recognition",
        "continual",
        "Wasserstein distance",
        "deception detection",
        "onboard charging",
        "Impedance",
        "Image and Video Synthesis Image Processing",
        "Benchmarking",
        "emotion perception",
        "GMM-based voice conversion",
        "Knowledge based systems",
        "End effectors",
        "Battery charge measurement",
        "Peer-to-peer computing",
        "Reinforcement learning",
        "self-rectifying",
        "Loading",
        "stochastic gradient methods",
        "Noise robustness",
        "Fast Fourier transforms",
        "Genomics",
        "Head",
        "electric vehicles",
        "Energy harvesting",
        "Attack",
        "Space-Time Transformation",
        "monostatic",
        "Poincar\\'e constant",
        "Reverse engineering",
        "Linguistics",
        "autism",
        "data processing inequalities",
        "Robot learning",
        "Interpolation",
        "Few-shot learning",
        "Jamming",
        "Optical sensors",
        "Object Detection",
        "Partitioning algorithms",
        "Invisible computing",
        "Big data",
        "Affective computing",
        "Tools",
        "Smart homes",
        "Immersive experience",
        "Depth sensing",
        "Behavioral science",
        "Scene Analysis",
        "PiB PET image",
        "frame interpolation",
        "Graph theory",
        "Backscatter communication",
        "Automobiles",
        "Frequency measurement",
        "real-to-sim transfer",
        "Bayesian nonparametrics",
        "mobile devices",
        "Array design",
        "Telecommunications",
        "Visual Reasoning",
        "Yarn",
        "user interface",
        "Dirichlet process",
        "Lottery pricing",
        "aqp",
        "Matrix converters",
        "Broadband communication",
        "Dark current",
        "learning curve",
        "language modeling",
        "classification algorithms",
        "deck recommendation",
        "Plasma waves",
        "Multimodal Imaging",
        "Laser radar",
        "mobile computing",
        "Soft robotics",
        "Distributed submodular maximization",
        "5G wireless network",
        "edge computing",
        "Road safety",
        "stochastic optimization",
        "Sun",
        "ConvAdapter",
        "cortical thickness based kernels",
        "Gomory-Hu tree",
        "deep neural network training",
        "Instant messaging",
        "Scene Inference",
        "Wireless Sensor Networks",
        "compositional learning",
        "Enclaves",
        "Video analytics",
        "clustering",
        "flexible",
        "Deep Neural Network",
        "Embryo",
        "cost-sensitive learning",
        "Harmonic analysis",
        "Hydraulic systems",
        "Robotics and automation",
        "quality of experience",
        "Production",
        "Microcomputers",
        "Wireless sensor networks",
        "Entropy",
        "Deep neural networks (DNNs)",
        "Documentation",
        "Bandwidth reduction",
        "Visual",
        "Deep convolutional neural network",
        "error detection",
        "Three-dimensional printing",
        "Reliability theory",
        "Disposable Domain Name",
        "Hippocampus",
        "Software",
        "Spectroscopy",
        "Physics",
        "classifier performance",
        "Calibration and identification",
        "Traffic signal control system",
        "Data privacy",
        "Structure from motion",
        "Open-World Learning",
        "Inspection",
        "human robot interaction",
        "maximization",
        "Outsourcing",
        "Humidity",
        "Power generation",
        "Virtual/augmented reality",
        "kernel-security",
        "Tuning",
        "Privacy preservation",
        "sampling",
        "Lithium-ion batteries",
        "Remote sensing",
        "social ambiance",
        "Recommendation Systems",
        "space-time coding",
        "Anthropometry",
        "Ports (Computers)",
        "Real-life trial",
        "Biomarkers",
        "video compression",
        "Electronic publishing",
        "social media",
        "Logic gates",
        "Image capture",
        "Band-pass filters",
        "Memory management",
        "visualization specification",
        "far field sensing",
        "Electron optics",
        "spoken dialog systems",
        "dynamic voltage and frequency scaling (DVFS)",
        "Arterial Performance Measures",
        "average-case",
        "Physiologic",
        "recurrent neural networks (RNNs)",
        "Authentication",
        "data",
        "Virtual Reality Based Independent Travel Training System for Children with Intellectual Disability",
        "Image restoration",
        "business intelligence querying",
        "Integrated circuits",
        "Industries",
        "reconfigurable PE",
        "hybrid sparse representation",
        "Quality of service",
        "Constructing Hardware in a Scala Embedded Language (Chisel)",
        "Fuzzing",
        "Rendering (computer graphics)",
        "Joining processes",
        "Vision",
        "Data aggregation",
        "Current measurement",
        "Accelerometers",
        "Videoconference",
        "mobile manipulation",
        "Probabilistic Inference",
        "Robotic-Vehicle",
        "never ending learning",
        "Ethics",
        "Polarization",
        "Prefix tuning",
        "ternary neural network",
        "Deep Reinforcement Learning",
        "linguistic",
        "Image sensing",
        "Radiometry",
        "Mathematical model",
        "Observers",
        "Climate change",
        "solver",
        "pervasive computing",
        "Face recognition",
        "Pyruvate",
        "Localization and Error Correction for Mobile Robot with an Image Sensor",
        "Education",
        "RISC-V",
        "coreless fiber",
        "wireless",
        "Surgery",
        "Video: Low-level analysis",
        "Databases",
        "Capacitors",
        "Complexity theory",
        "context awareness",
        "Boosting",
        "Parallel algorithms",
        "Transportation industry",
        "Deformable models",
        "Alzheimer's disease",
        "human activity recognition",
        "Similarity Learning",
        "Collision avoidance",
        "Simulation",
        "Internet/Web technologies",
        "Obstacle Avoidance System for Wheeled Mobile Robots by CMOS Image Sensors",
        "Intrusion detection",
        "awareness",
        "Optical variables control",
        "Wheels",
        "polyvinylidene fluoride",
        "Painting",
        "neuron coverage",
        "Three dimensional displays",
        "regularity lemma",
        "linear program",
        "Fourier transforms",
        "Buffer overflow",
        "Magnetic resonance imaging",
        "Mixed reality",
        "cost function",
        "multicore",
        "Handheld",
        "optical neural networks",
        "component",
        "Attention mechanism",
        "Shape",
        "Propulsion",
        "Autonomous automobiles",
        "stochastic computing G (GEMM) is ubiquitous and essential in many applications",
        "Heart Rate",
        "Vocabulary",
        "feature extraction",
        "Hardware security module (HSM)",
        "realtime",
        "Virtual private networks",
        "environmental monitoring",
        "spatial layouts",
        "Image coding",
        "Oscillators",
        "low-power wireless system",
        "Time factors",
        "Kalman filters",
        "automatic tuning",
        "Approximation methods",
        "Face",
        "Maintenance engineering",
        "Embodied vision: Active agents",
        "Digital video broadcasting",
        "Text recognition",
        "Condition-based maintenance",
        "human-robot interaction",
        "information extraction",
        "Acoustic sensors",
        "segmental models",
        "Markov chain",
        "Parity check codes",
        "Signal processing",
        "Berkeley Analog Generator (BAG)",
        "file synchronization",
        "Atmospheric waves",
        "Scalability",
        "High frequency Transformer",
        "databases",
        "In vitro",
        "Leak detection",
        "Frequency estimation",
        "Electronic medical records",
        "Redundancy",
        "Autotuning",
        "DTW Distance",
        "local differential privacy",
        "Attitude sensor",
        "Process design",
        "computational complexity.",
        "Anomaly detection",
        "2014 Tenth International Conference on Intelligent Information Hiding and Multimedia Signal Processing",
        "Low Error Rates",
        "hackers",
        "Datasets and evaluation; Video analysis and understanding",
        "Edit Distance",
        "task planning",
        "impedance matching",
        "Multiple Wavelength",
        "Organizing",
        "classification",
        "Electric fields",
        "computing",
        "Biomedical measurement",
        "image enhancement",
        "intersection of halfspaces",
        "Clothing",
        "Mobile data collection",
        "Explosions",
        "Event-based social networks",
        "derandomization",
        "Power harmonic filters",
        "Fans",
        "routing games",
        "Child",
        "Reflection",
        "Published: 2006",
        "uncertainty",
        "Cerebral Cortex",
        "Base stations",
        "Block codes",
        "Simulation Applications",
        "Function approximation",
        "trusted execution environment (TEE)",
        "low-complexity decoding",
        "Semiconductor lasers",
        "non-persistent data",
        "Turbo codes",
        "convolutional neural networks",
        "pattern recognition",
        "Fish",
        "Candidate Retrieval",
        "Multitasking",
        "radar signal processing",
        "Sensitivity",
        "Location awareness",
        "spectrometer",
        "Least squares approximations",
        "Prediction algorithms",
        "Image recognition",
        "hashing",
        "Wi-Fi",
        "scalability",
        "online learning",
        "dynamic column redundancy (DCR)",
        "Optical pulse generation",
        "reprogrammable redundancy (RR)",
        "Boolean algebra",
        "Doped fiber amplifiers",
        "Cross-platform Prediction",
        "Scene Analysis and Understanding",
        "Magnetic sensors",
        "Static analysis",
        "Bending",
        "IEEE 802.15 Standard",
        "Resting-state fMRI",
        "Edge Cloud",
        "Vegetation",
        "3D printing",
        "human-powered device.",
        "Self-supervised or unsupervised representation learning",
        "Adaptive systems",
        "range sensing",
        "Seed-Scheduler",
        "Thin-shell conjecture",
        "Measurement",
        "Formal verification",
        "Emergency services",
        "computer security",
        "Vaccines",
        "Intelligent robots",
        "information visualization education",
        "Concentration",
        "compute-and-forward",
        "attack-synthesis",
        "Humans",
        "transformer design",
        "Avatars",
        "haptics and haptic interfaces",
        "pose",
        "Algorithmic Graph Theory",
        "regular expression matching",
        "Autonomous systems",
        "wavelets on graphs",
        "global variance",
        "Code Mining",
        "Computer languages",
        "mobile",
        "Computational imaging",
        "zero-shot models",
        "Segmentation and Categorization",
        "Scanning electron microscopy",
        "SGX",
        "inference understanding",
        "approximation algorithms",
        "Grasping",
        "fifth-generation reduced instruction set computer (RISC-V)",
        "Chip-multiprocessors",
        "Type-Inference",
        "Joints",
        "Multiplication-reduced hybrid networks",
        "Solid state circuits",
        "reference mask",
        "Ad hoc networks",
        "Ecosystems",
        "parallel programming",
        "hardware",
        "object detection",
        "Polynomials",
        "Power system stability",
        "Multi view",
        "ARMA prediction",
        "Testing",
        "physics computing",
        "Phase measurement",
        "Activity Recognition",
        "Bicycles",
        "Shape measurement",
        "IP networks",
        "API mining",
        "Multimodal graphs",
        "graph neural networks",
        "low-precision arithmetic",
        "low-density parity-check (LDPC) code",
        "Educational institutions",
        "meta",
        "Modelling",
        "Neural radiance field",
        "graphene optoelectronics",
        "Embedded sensing/real-time techniques",
        "IDE",
        "Biomedical monitoring",
        "Patient monitoring",
        "Web services",
        "Automatic speech recognition",
        "Image quality",
        "functional networks",
        "post-filter",
        "Image retrieval",
        "log message",
        "Sentiment analysis",
        "Video analysis and understanding; Vision + language",
        "IEEE Access",
        "Connectors",
        "Real-Time Travel Time Estimation",
        "low-rank approximation",
        "Internet of Things",
        "Faces",
        "usability of programming languages",
        "Power system management",
        "RBAC",
        "Spatiotemporal phenomena",
        "active learning",
        "action units",
        "strong duality",
        "Optical films",
        "Clustering",
        "CNTFETs",
        "Chemicals",
        "database query processing",
        "Performance Modeling",
        "time-of-flight",
        "sums of independent random variables",
        "Media Impact",
        "Image sequences",
        "subgraph isomorphism",
        "Crowdsourcing",
        "multivariate graphs",
        "Transfer Learning",
        "Optical mixing",
        "Throughput",
        "Semisupervised learning",
        "Market research",
        "Plasma applications",
        "non-intrusive visible communication",
        "initialization",
        "Sensor phenomena and characterization",
        "LoRA",
        "Image and Video Synthesis",
        "image modification",
        "glow discharge",
        "bidirectional encoder representations from transformers",
        "Nominations and elections",
        "Multimodal dataset",
        "Physically-based simulation",
        "Vehicle-to-everything",
        "control frame",
        "sublinear time algorithms",
        "graph algorithms",
        "safety",
        "visualization design",
        "Redirected Walking",
        "User experience",
        "Process control",
        "Web server",
        "Nanophotonics",
        "multilingual speech recognition",
        "resource allocation",
        "Telecommunication traffic",
        "Sorting",
        "Superresolution",
        "Kernel",
        "scene classification",
        "Vehicle Re-Identification",
        "Data mining",
        "Buildings",
        "Active cancellation",
        "Birds",
        "behavioral imaging",
        "Cognition",
        "fully integrated converter",
        "Differential privacy",
        "Algorithms: Computational photography",
        "Self-& semi-& meta- Machine learning",
        "heart failure",
        "Boustrophedon",
        "macro vision",
        "Low voltage",
        "Radio frequency fingerprinting",
        "Arrays",
        "Skeleton",
        "energy-efficient accelerator",
        "Gold",
        "Network Design",
        "Energy substrate",
        "attributes",
        "Recent Advances of Generative Adversarial Networks in Computer Vision",
        "communicative visualization",
        "Counter terrorism",
        "vegetation mapping",
        "Adversarial Robustness",
        "3D from Multiview and Sensors",
        "Target tracking",
        "Optical computing",
        "Transformer cores",
        "Image Processing -> Image Restoration",
        "limit theorem",
        "Optical fiber sensors",
        "data security.",
        "Algorithms: Machine learning architectures",
        "Real time systems",
        "reusable garbled RAM",
        "Motion segmentation",
        "synthetic aperture radar",
        "Delays",
        "deep-packet inspection",
        "development",
        "Published: 2022",
        "2006 SICE-ICASE International Joint Conference",
        "multi-chip modules",
        "spectrum sensing",
        "GPS spoofing attack",
        "neural networks",
        "Thermal analysis",
        "weak labeling",
        "Pipelines",
        "Cleaning",
        "Cavity resonators",
        "autonomous vehicle",
        "Image and video synthesis and generation",
        "Database systems",
        "Convolution neural network",
        "Internet and Web services",
        "Stress",
        "Functional magnetic resonance imaging",
        "stationary distribution",
        "(230.7370) Waveguides",
        "Symbols",
        "Communities",
        "Heart rate",
        "injection molding",
        "Binary phase shift keying",
        "Fault injection",
        "60 GHz",
        "Trojan horses",
        "Electrocardiography",
        "Communicative motion",
        "cyber-security",
        "Postal services",
        "object recognition",
        "Fungi",
        "Optimal scheduling",
        "Probability distribution",
        "style",
        "forecasting stability events",
        "Accelerator architectures",
        "imitation learning",
        "Google",
        "Muscles",
        "Fault tolerant systems",
        "Design of Mathematical Online Training Interactive Framework based on AI-assisted Data Modeling Algorithm Visualization Process",
        "Adapters",
        "nearly linear time",
        "Optical beams",
        "t-distributed stochastic neighbor embedding",
        "Fabrication",
        "card",
        "Transfer/low-shot/long-tail learning; Machine learning",
        "Gaussian distribution",
        "Circuit faults",
        "Discrete-Event",
        "Decorrelation",
        "Data poisoning",
        "user behavior analysis",
        "Instruction sets",
        "Flowering plants",
        "Frequency modulation",
        "lexical variation",
        "ecology",
        "Deep neural networks",
        "Haptic interfaces",
        "Semiconductor device modeling",
        "face-recognition",
        "Floors",
        "Reproducibility of Results",
        "Transistors",
        "Bioinformatics",
        "artificial intelligence",
        "Malware",
        "hardware accelerators",
        "Robotics",
        "field programmable gate array",
        "Physiology",
        "Advertising",
        "distance learning",
        "segmentation",
        "bitonic sort",
        "Helicopters",
        "Snow",
        "Optical variables measurement",
        "Power lasers",
        "Silver",
        "ubiquitous computing",
        "polynomial threshold function",
        "Strain",
        "secretary problem",
        "phased arrays",
        "Pressure measurement",
        "reusable garbled circuits",
        "data anonymization",
        "Software testing",
        "MATLAB",
        "Visualization taxonomy",
        "Diseases",
        "optimal design",
        "Electrodes",
        "DC motors",
        "Printers",
        "Bayesian networks",
        "Statistical",
        "Fluids",
        "speech synthesis",
        "conditional policies",
        "power amplifier",
        "submodular functions",
        "Storms",
        "Time measurement",
        "Retrieval",
        "Business",
        "Humans: Face",
        "Jitter",
        "Set theory",
        "Internet",
        "Morphology",
        "Message passing",
        "Kernel Drivers",
        "Yttrium",
        "Built Environment",
        "data mining",
        "formal methods",
        "Text/Document Data",
        "hippocampus",
        "Object Interaction",
        "pervasive",
        "Inductance",
        "Graphics processing units",
        "Global Positioning System",
        "operator interfaces",
        "distribution learning",
        "simultaneous transmission and reception (STR)",
        "Remuneration",
        "Autonomous underwater vehicles",
        "interior point method",
        "Rain",
        "ethics in vision",
        "Excitons",
        "MIMO communication",
        "generative models",
        "Laser beams",
        "Action Dataset",
        "multiplex network",
        "Statistical analysis",
        "Reduced instruction set computing",
        "Affordances",
        "information measure",
        "Coherence",
        "Advantage Estimation",
        "Conferences",
        "NOMA",
        "Wires",
        "Ovens",
        "green computing",
        "accelererometer",
        "harassment",
        "reconstruction",
        "deep feature learning",
        "eye tracking",
        "Needles",
        "speech recognition",
        "on-device processing",
        "Thumb",
        "brain network",
        "Non-malleable codes",
        "Locomotion",
        "Risk communication",
        "vegetation",
        "coupling enhanced",
        "Linear systems",
        "Navigation",
        "Atmospheric measurements",
        "Electrical engineering",
        "Stereo vision",
        "Published: 2016",
        "Biomimetics",
        "gender-based word disambiguation",
        "Property testing",
        "styling",
        "Image motion analysis",
        "payoff inference",
        "Attack Detection",
        "non-line-of-sight reconstruction",
        "neural object representations",
        "Ballistocardiography",
        "Linear algebra",
        "Computer Simulation",
        "FT",
        "Tor network",
        "Computer bugs",
        "Aggregation control",
        "sensor-based control",
        "Aerospace electronics",
        "EGFP",
        "remote sensing",
        "Power line communications",
        "Optical fibers",
        "machine learning security",
        "Headphones",
        "content distribution network",
        "dynamic functional connectivity",
        "Optical imaging",
        "Speech Processing",
        "Multi-robot systems",
        "sleep tracking",
        "Optical fiber communication",
        "Open systems",
        "Stability analysis",
        "Containers",
        "intersection movement assist",
        "project Fi",
        "narrative structure",
        "(130.3120) Integrated optics devices",
        "Debugging",
        "Benchmark testing",
        "System-on-chip",
        "Phase shift keying",
        "linear algebra querying",
        "Image segmentation",
        "automated-program-repair",
        "shape completion",
        "Communicative visualization",
        "Binary codes",
        "Sensors",
        "Phishing attacks",
        "Light emitting diodes",
        "Speech",
        "Machine learning",
        "modulation spectrum",
        "Magnetic hysteresis",
        "Fading channels",
        "autonomous agents",
        "User interfaces",
        "Sequence Recovery",
        "Multiaccess communication",
        "Temperature sensors",
        "Cues",
        "Design engineering",
        "Monotonicity testing",
        "Communication system security",
        "Binary-Transformation",
        "group popularity prediction",
        "Visual odometry",
        "Low Light",
        "kernel density estimation",
        "power amplifier (PA)",
        "mobile video chats",
        "Denoising",
        "Real-time systems",
        "Wireless systems",
        "Image synthesis",
        "Biological",
        "Dimensionality reduction",
        "battery management system (BMS)",
        "Informatics",
        "energy efficiency",
        "robotic manipulation",
        "Artificial neural networks",
        "Simulation and animation",
        "radio-frequency identification (RFID) technology",
        "Measure concentration",
        "Power distribution",
        "Accuracy",
        "segmentation and categorization",
        "Optical refraction",
        "Computer science",
        "foundations of machine learning",
        "Reverse-Engineering",
        "Machine learning architectures and formulations",
        "Rats",
        "Representation learning; Recognition: detection",
        "Europe",
        "Few-Shot Learning",
        "Indexes",
        "parallel complexity",
        "Transforms",
        "Receivers",
        "Iterative methods",
        "daily life monitoring",
        "Wheelchairs",
        "Datasets and Evaluation",
        "Deep architecture",
        "USA Councils",
        "Transformer",
        "projection pruning",
        "hidden visible communication",
        "Java",
        "Command and control systems",
        "Privacy",
        "Stochastic processes",
        "Dynamic range",
        "Intel SGX",
        "Slicing conjecture",
        "Autism",
        "Application-Security",
        "global landscape",
        "Performance gain",
        "Small-depth circuits",
        "Question answering (information retrieval)",
        "System Security",
        "random walks",
        "Passive networks",
        "design methodology",
        "Toxicology",
        "Transparency",
        "role discovery",
        "Components",
        "visual reasoning)",
        "Nash equilibrium",
        "Learning objectives",
        "algorithm-hardware co-design",
        "Data security",
        "Codes",
        "Published: 2014",
        "intelligent sensors",
        "quantity",
        "irregular programs",
        "shared antenna interface",
        "Generative Models",
        "Sensor systems and applications",
        "Scan statistics",
        "Mirrors",
        "TDD front-end",
        "Vision + language",
        "Behavioral sciences",
        "Python",
        "load following",
        "Optimization methods",
        "Embedded systems",
        "post-processing",
        "Amplitude modulation",
        "Query processing",
        "Machine learning; Others",
        "Support Vector Machines",
        "Tutorials",
        "Laplacian",
        "IEEE 802.11 Standards",
        "acoustic",
        "backdoor attacks",
        "Discrete Fourier transform",
        "Electromyography",
        "energy storage system (ESS)",
        "Graphite",
        "Density measurement",
        "root-cause analysis",
        "Bars",
        "monitoring",
        "Automata",
        "Clamps",
        "Cheeger constant",
        "process mining",
        "topic modeling",
        "Phishing",
        "Alignment",
        "micro/nano robots",
        "Lattices",
        "visualization",
        "class imbalance",
        "Facial features",
        "Stationary state",
        "Medical devices",
        "Computational Optics",
        "CAD",
        "high performance",
        "Checkpointing",
        "Heating",
        "3D vision",
        "Backscatter",
        "Signal to noise ratio",
        "Geographic Routing",
        "Integrated design",
        "Fault diagnosis",
        "Multi-Agent",
        "Online services",
        "Acceleration",
        "Optical vortices",
        "Markov decision processes",
        "Text mining",
        "Analog-to-digital converters (ADCs)",
        "Scene text and document understanding",
        "Gears",
        "Pricing",
        "Classification",
        "Minimally invasive surgery",
        "Fasteners",
        "Pattern matching",
        "Automotive engineering",
        "pseudohaptics",
        "Recurrent neural networks",
        "Implants",
        "Data integrity",
        "collaboration",
        "Sensor fusion",
        "Signal Matching",
        "Vision applications and systems",
        "natural user interface",
        "voltage and cell balancing",
        "temporal upsampling",
        "Jacobian matrices",
        "Glucose",
        "Speech processing",
        "Collaboration",
        "Random access memory",
        "Information technology",
        "or long-tail learning",
        "bidirectional",
        "FinFET",
        "Annotations",
        "DRAM chips",
        "over-smoothing",
        "unsupervised unit discovery",
        "Large-scale systems",
        "Switches",
        "Immune system",
        "Efficient training and inference methods",
        "Knowledge transfer",
        "Program Obfuscation",
        "Spatial resolution",
        "Servers",
        "software security",
        "real-time",
        "Optics",
        "RFID tags",
        "heart rate estimation",
        "graph theory",
        "Neural networks",
        "receiver complexity",
        "Spraying",
        "Channel Coding",
        "Stock markets",
        "Service-oriented architecture",
        "program synthesis",
        "Video equipment",
        "Regression Analysis",
        "submodular optimization",
        "Cancer",
        "Iterative decoding",
        "5G mobile communication",
        "asynchrony",
        "central limit theorems",
        "PageRank",
        "Performance evaluation",
        "pedagogy",
        "Lead",
        "sustainability",
        "Pragmatics",
        "simulation",
        "statistics",
        "Modulation",
        "Detection and localization in 2D and 3D",
        "Optical reflection",
        "data imbalance",
        "deep neural networks",
        "IEC Standards",
        "Drone",
        "Observability",
        "High energy physics instrumentation computing",
        "anomaly detection",
        "Recording",
        "Multivariate statistics",
        "Edge Computing",
        "diagonally dominant",
        "gestures",
        "thermal features",
        "detectors",
        "multitask training",
        "Rough surfaces",
        "Heuristic algorithms",
        "Demand response",
        "Local Binary Pattern",
        "Information services",
        "generators",
        "seizure detection",
        "Phase noise",
        "ultrasonic wavefront",
        "Adversarial Defense",
        "3G mobile communication",
        "information flow analysis",
        "nonintrusive load monitoring",
        "Computing methodologies-Virtual reality",
        "set visualization",
        "Dual Active Bridge",
        "Nonvolatile memory",
        "MRI",
        "Automation",
        "Content distribution networks",
        "formatting",
        "Logconcave distributions",
        "Boolean functions",
        "symbol grounding",
        "Eyebrows",
        "Visually Impaired Persons",
        "Computational modeling",
        "Green design",
        "join processing",
        "mobile device",
        "millimeter wave",
        "adapting clock rate",
        "Benchmark",
        "Videos",
        "system-on-chip (SoC)",
        "tamper-resilient cryptography",
        "and reasoning",
        "Path Planning for Multiple Mobile Robots or Agents",
        "magic lens",
        "Reliability",
        "automation",
        "concurrent-program-testing",
        "retrieval; Representation learning",
        "Markov Chain Monte Carlo",
        "computer vision for other robotic applications",
        "Graphical models",
        "invariant group",
        "Gibbs sampling",
        "gan",
        "security property",
        "mouse brain",
        "Stakeholders",
        "Diversity reception",
        "Standards",
        "Filtering",
        "geodesic regression",
        "Technical Activities Guide - TAG",
        "fast Fourier transform",
        "Adders",
        "Robot navigation",
        "Abstracts",
        "Analytical models",
        "Magnetomechanical effects",
        "Domain specific languages",
        "Vehicle detection",
        "formulations",
        "self-interference (SI) cancellation (SIC)",
        "Image denoising",
        "cloud",
        "power management unit (PMU)",
        "DC–DC conversion",
        "microwave tunable filter.",
        "inference extensibility",
        "Convergence",
        "haptic device",
        "Video on demand",
        "System recovery",
        "Pneumatic systems",
        "high level synthesis",
        "simultaneous-switching",
        "Indium tin oxide",
        "Markov random fields",
        "User-Computer Interface",
        "Virtual machining",
        "low-shot",
        "common sense relationships",
        "honeywords",
        "infovis",
        "optimization design",
        "Multicore processing",
        "Protocols",
        "Sensor arrays",
        "Sea floor",
        "encryption",
        "bug detection",
        "Visual Perception",
        "DPI",
        "2022 International Conference on Inventive Computation Technologies (ICICT)",
        "failure diagnosis",
        "Microarchitecture",
        "Manufacturing",
        "Classification algorithms",
        "manifold statistics",
        "Augmented Reality",
        "Bit bypass (BB)",
        "Lindeberg method",
        "Electroencephalography",
        "Decompilation",
        "Fabrics",
        "smell",
        "garbage collection",
        "matrix sensing",
        "tabletop robotics",
        "unstructured sparsity",
        "Design methodology",
        "hardware accelerator",
        "Phonetics",
        "line disable (LD)",
        "single-ended signaling",
        "end-to-end training",
        "Phantoms",
        "Statistical learning",
        "Microstructure",
        "Threat modeling",
        "Photovoltaic systems",
        "Photonic crystals",
        "social robotics",
        "universal phone recognition",
        "Fuels",
        "Biomass",
        "accelerator",
        "ASD",
        "nonconvex matrix factorization",
        "key management service (KMS)",
        "Multi-modal learning",
        "camera",
        "data analysis",
        "Parallel Computing",
        "security economics",
        "Spoken named enitiy recognition",
        "manipulation planning",
        "testing",
        "Probability",
        "Image classification",
        "Coordinate measuring machines",
        "course success prediction",
        "Sustainable development",
        "Solid State Transformer",
        "Blood",
        "feedback communication",
        "Surface roughness",
        "photonic crystals",
        "usage data",
        "T/R switch",
        "hydraulic bed sensor",
        "leverage score sampling",
        "Fluctuations",
        "random projection",
        "chunk-based accelerator",
        "non-orthogonal multiple access",
        "Signal analysis",
        "Data visualization",
        "Frequency conversion",
        "static analysis",
        "differentiable contact simulation",
        "Turbo Principle",
        "RGB-D perception",
        "annotation",
        "Manipulator dynamics",
        "unknown-view tomography",
        "Convex functions",
        "Computational linguistics",
        "Learning",
        "dissemination",
        "Decision support systems",
        "vector",
        "non-line-of-sight imaging",
        "ground-referenced signaling (GRS)",
        "time-series data",
        "minimal supervision",
        "Surface texture",
        "Risk",
        "processing-in-memory",
        "SPR",
        "MapReduce",
        "HMM-based text-to-speech",
        "Hazards",
        "identification",
        "liability",
        "Symbolic execution",
        "retrieval; Transfer/low-shot/long-tail learning",
        "Limit theorem",
        "bidirectional LSTM",
        "Cloud computing",
        "switched-capacitor PA (SCPA)",
        "Hybrid Memory",
        "Video inpainting",
        "individual differences.",
        "recognition of table",
        "software-testing",
        "Driver circuits",
        "Routing",
        "visuo-proprioceptive cues",
        "Desirable difficulites",
        "Optical receivers",
        "Published: 2012",
        "Program processors",
        "Optical waveguides",
        "integration and modeling",
        "Peer to peer computing",
        "Image representation",
        "Decision trees",
        "Time-frequency analysis",
        "Windings",
        "NLP",
        "sliding window",
        "non-euclidean",
        "Array signal processing",
        "Linear programming",
        "Measurement by laser beam",
        "Activity recognition",
        "tracking",
        "Optical switches",
        "backscatter communication",
        "OFDM",
        "DRAM",
        "Meetings",
        "switched-capacitor",
        "millimeter-wave (mm-wave) arrays",
        "Fading",
        "Exploratory Visualization of Surgical Training Databases for Improving Skill Acquisition",
        "QoE",
        "Picture archiving and communication systems",
        "Transceivers",
        "software performance",
        "population recovery",
        "Side-channel attacks",
        "sliding window model",
        "Voronoi",
        "Censorship",
        "Compressive Sensing",
        "affective computing",
        "Inductors",
        "telemanipulation",
        "deep learning",
        "Software radio",
        "persistent memory",
        "hypothesis selection",
        "Latches",
        "key derivation",
        "wavelets",
        "Natural language processing",
        "Noise",
        "Production facilities",
        "Solid modeling",
        "Wireless LAN",
        "Propagation losses",
        "Clutter",
        "optimization and optimal control",
        "Blogs",
        "stochastic rounding",
        "Inference algorithms",
        "source inference",
        "Bidirectional DC/DC",
        "Explainable computer vision",
        "Motion capture",
        "stability",
        "smart environments",
        "Lithium",
        "Psychology",
        "Automatic program testing",
        "inertial generator",
        "Heart Failure",
        "Pattern recognition",
        "Waveguide lasers",
        "Voltage measurement",
        "information retrieval",
        "3D reconstruction",
        "Batteries",
        "scheduling algorithms",
        "Training data",
        "Metadata",
        "Computing methodologies-Intelligent agents",
        "Public key",
        "Data models",
        "Directed graphs",
        "Water heating",
        "tab",
        "Power measurement",
        "computational optics",
        "recursive projection-aggregation (RPA) decoding",
        "Permission",
        "Ballistocardiogram (BCG)",
        "Cryptography",
        "diffusion weighted images",
        "cardiac output",
        "Training",
        "Millimeter wave radar",
        "Object Usage Sensing",
        "mobile security",
        "impersontation",
        "depthmap",
        "graph matching",
        "model predictive control",
        "Cost accounting",
        "image classification",
        "Ergodic",
        "Discussion forums",
        "Digital twins",
        "thermal imaging",
        "Network architecture",
        "Computer architecture",
        "multi-carrier network access",
        "Submodular Functions",
        "narrowband IoT (NB-IoT)",
        "localization",
        "consistency",
        "blood volume pulse (BVP)",
        "Interactive machine learning",
        "situational awareness",
        "Fires",
        "Neural Networks",
        "Greedy algorithms",
        "graphite",
        "Roads",
        "Autonomous aerial vehicles",
        "Mathematical models",
        "Substrates",
        "probability",
        "Encyclopedias",
        "Semantic segmentation",
        "developers' incentives",
        "Optimized production technology",
        "Image edge detection",
        "Cities and towns",
        "Rust",
        "Phase Retrieval",
        "Semantics",
        "Thermal sensors",
        "Distortion",
        "Shortest path problem",
        "image processing",
        "Visualization system and toolkit design",
        "Big Data",
        "Self-supervision",
        "Convolutional neural networks",
        "matrix games",
        "dynamic frequency scaling.",
        "Ethernet networks",
        "Multiplexing",
        "statistical relational models",
        "Convolutional codes",
        "multi-user multiple-input–multiple-output (MU-MIMO)",
        "computational imaging",
        "Students",
        "Decoding",
        "Laplace equations",
        "Software-security",
        "Numerical Linear Algebra",
        "LIDAR",
        "Q-learning",
        "quality of results",
        "Service robots",
        "interaction design",
        "Control systems",
        "Silicon",
        "Laser modes",
        "Fingers",
        "retrieval; 3D from multi-view and sensors; Navigation and autonomous driving; Transfer/low-shot/long-tail learning",
        "peer learning",
        "nonnegative matrix factorization",
        "narrative visualization",
        "Alzheimer's Disease Neuroimaging Initiative (ADNI)",
        "Symbiosis",
        "Transfer learning",
        "Absorption",
        "Uplink",
        "rapid design",
        "Adversarial",
        "Lighting",
        "geospatial analysis",
        "Object Recognition",
        "CIFAR",
        "Microcavities",
        "Software packages",
        "eXplainable AI",
        "sensor fusion",
        "Optical modulation",
        "corrosion",
        "Gaussian processes",
        "Movement",
        "Universal Serial Bus",
        "Applied probability",
        "structured sparsity",
        "Computational modelling",
        "Data Curation",
        "Acoustics",
        "Real-time scheduling",
        "head-mounted wearable device",
        "Literacy",
        "refactoring",
        "Routing protocols",
        "multimedia and graphics",
        "Data augmentation",
        "Maximum flow",
        "cloud computing",
        "Mobile communication",
        "Portable media players",
        "Programming profession",
        "two-stage beamforming",
        "Force and tactile sensing",
        "Polynomial Hierarchy",
        "Lactate",
        "olfactory display",
        "Graph-Analysis",
        "Hidden Markov models",
        "Computer-Assisted",
        "Tagging",
        "Quality of experience",
        "Business intelligence",
        "sketching",
        "Humanoid robots",
        "Computer network reliability",
        "Object segmentation",
        "DVD",
        "Visual analytics",
        "Teamwork",
        "RFID",
        "evaluation",
        "subgraph pattern",
        "Grounding",
        "Image color analysis",
        "Olfaction",
        "spores",
        "Wireless communication",
        "dataset security",
        "self-monitoring",
        "particle physics",
        "Reconfigurable Computing",
        "Animation",
        "Structure",
        "Computer Graphics",
        "Phased arrays",
        "engagement",
        "Footnotes",
        "Doppler shift",
        "GPU",
        "tree traversals",
        "GeoNetworking",
        "Vision + other modalities",
        "Transaction",
        "Wool",
        "MeSH Terms",
        "24-GHz band",
        "EMG",
        "Internet of things",
        "Mobile apps",
        "Categorization",
        "Instance-aware semantic segmentation",
        "Robot safety",
        "Couplings",
        "Graph Alignment",
        "Mood tracking",
        "reliability",
        "field robots",
        "retrieval; Self-& semi-& meta- Transfer/low-shot/long-tail learning; Vision + language",
        "safety management",
        "Problem-solving",
        "Radiation detectors",
        "LSPR",
        "Writing",
        "power",
        "Elbow",
        "Size measurement",
        "random walk",
        "Neurons",
        "Deep learning in robotics and automation",
        "honey encryption",
        "Automated Program Repair",
        "P2P",
        "Video analysis and understanding; 3D from multi-view and sensors; Deep learning architectures and techniques",
        "Event detection",
        "Model inference",
        "Statistical parametric speech synthesis",
        "Robot kinematics",
        "Runtime",
        "WiMAX",
        "Autonomous robots",
        "Low-noise amplifier",
        "Programming",
        "weight pruning",
        "Vehicle to Load (V2L)",
        "programming language",
        "Power capacitors",
        "Expander decomposition",
        "Accidents",
        "Fingerprint recognition",
        "High-voltage techniques",
        "Turning",
        "Layout",
        "Degradation",
        "Mobility prediction",
        "Mobile computing",
        "Motion and Path Planning",
        "Noise measurement",
        "Glass",
        "Signal processing algorithms",
        "language",
        "Error correction codes",
        "Impact of Full-Body Avatars in Immersive Multiplayer Virtual Reality Training for Police Forces",
        "Monopoly",
        "Convex Geometry",
        "Android fragmentation",
        "Feature extraction",
        "Device drivers",
        "heart rate",
        "Journalism",
        "Connected Vehicles",
        "Dynamic programming",
        "Vehicles",
        "memorability",
        "Media",
        "Concurrent computing",
        "Image processing",
        "Ontologies",
        "Linux",
        "Connectionist temporal classification",
        "Simulated annealing",
        "N-version system",
        "Prosthetic hand",
        "Symmetric matrices",
        "International relations",
        "Convolutional Neural Network",
        "4G mobile communication",
        "Distributed Computing",
        "quantization",
        "Anomaly Detection",
        "Artificial Intelligence",
        "electric vehicle",
        "Programmable logic arrays",
        "em-pirical study of programming languages",
        "Counting circuits",
        "ideation metrics",
        "nonlinearity",
        "DNSSEC",
        "Factory automation",
        "Vectors",
        "Non-line-of-sight",
        "Simulation and Animation",
        "text processing",
        "computer graphics",
        "Dimension reduction",
        "network security",
        "systems architectures",
        "hardware-software-co-design",
        "Pedestrians",
        "Keyboards",
        "Wearable sensors",
        "Full-duplex (FD) radio",
        "ADMM",
        "AWGN channels",
        "approximate query processing",
        "elasticity recovery",
        "Computer applications",
        "sums of independent integer random variables",
        "Recognition: detection",
        "multivew",
        "Tactile sensors",
        "oversmoothing",
        "random projections",
        "Lawn-mower",
        "Channel coding",
        "Stochastic gradient descent",
        "DNA",
        "On-board Charger",
        "Pervasive computing",
        "Optical surface waves",
        "Vehicular ad hoc networks",
        "Binary-Analysis",
        "cloud providers",
        "Surface waves",
        "Bimodal Modeling",
        "ℓ_∞ regression",
        "Antenna arrays",
        "Method of moments",
        "Autonomous vehicles",
        "change detection",
        "Sparsification",
        "Wiring",
        "self erasing memory",
        "Planning",
        "Schedules",
        "Grammar",
        "Social robots",
        "olap",
        "Manifolds",
        "Eigenvalues and eigenfunctions",
        "Spectral Graph Methods.",
        "Stochastic computing",
        "Intelligent agents",
        "Telepresence",
        "Photodiodes",
        "OOV detection",
        "Approximate Message Passing",
        "Brain",
        "query complexity",
        "ubicomp",
        "low current",
        "Network topology",
        "Computer",
        "haptic feedback",
        "Bipartite graph",
        "tunable generator",
        "parallel computing",
        "US Department of Defense",
        "emerging-threats",
        "Natural languages",
        "Receiving antennas",
        "Surface cleaning",
        "Medical robotics",
        "ubiquitous",
        "Differential equations",
        "code-reuse attack",
        "Engines",
        "Computational photography; Physics-based vision and shape-from-X",
        "Social sciences",
        "Memristors",
        "Web",
        "Gomory Hu tree",
        "Hardware design languages",
        "Telerobotics and Teleoperation",
        "Genetic algorithms",
        "usability",
        "multiple views",
        "Cows",
        "linguistic features",
        "model interpretability",
        "Structural rings",
        "high-performance computing",
        "Cells (biology)",
        "Graph isomorphism",
        "Field effect transistors",
        "Terrorism",
        "Deep neural network (DNN)",
        "Alzheimer’s Disease",
        "Processor scheduling",
        "Image sequence analysis",
        "Electronic commerce",
        "Urban areas",
        "declarative specification",
        "Sparse representation",
        "Game theory",
        "unsupervised learning",
        "Length measurement",
        "Edge computing",
        "security testing platform",
        "(010.1330) Atmospheric turbulence",
        "Delay",
        "Classroom feedback systems",
        "Context modeling",
        "Synthesizers",
        "learning from demonstration",
        "Real-time software",
        "Safety",
        "network-security",
        "semi-supervised learning",
        "Human computer interaction",
        "unit-demand buyer",
        "Datasets and evaluation",
        "contact modeling",
        "tactile exploration",
        "virtual machine introspection",
        "Monte Carlo methods",
        "Motion and path planning",
        "Human in the loop",
        "Virtualization",
        "digital-to-analog converter (DAC)",
        "Multimodal learning",
        "PA re-use",
        "Range Sensing",
        "Inverters",
        "More Like This",
        "Robust Optimization",
        "Corrosion",
        "filter",
        "Computer Vision for Automation",
        "spatial multiplexing",
        "deep neural network (DNN)",
        "Somatic cell nuclear transfer",
        "Self-supervised learning",
        "accelerated coordinate descent",
        "3D Computer Vision Object Detection/Recognition/Categorization",
        "Organizations",
        "Embedded computing",
        "Radiofrequency identification",
        "Telephone sets",
        "physics-inspired deep model",
        "security and privacy",
        "finite automata",
        "numerical linear algebra",
        "Bridges",
        "Forestry",
        "Multiparty Computation",
        "Resonant frequency",
        "Generative models",
        "Surface fitting",
        "Gaze tracking",
        "random matrix theory",
        "Engineering students",
        "Sociology",
        "Physical design",
        "Hafnium",
        "Torque",
        "Decision making",
        "Low Power",
        "fast Fourier transform (FFT)",
        "Control",
        "Three-dimensional displays",
        "Heating systems",
        "Syntactics",
        "Learning from source code",
        "Transformers",
        "Software engineering",
        "Learning systems",
        "Parallel robots",
        "Photonics",
        "Information integrity",
        "quality",
        "Source separation",
        "Mechanical systems",
        "Belief propagation",
        "contactless cavity resonator",
        "Filtering algorithms",
        "Millimeter wave communication",
        "Virtual reality",
        "Computational Photography",
        "Feedback Channel",
        "Qubit",
        "details-on-demand",
        "Propagation",
        "Deep learning",
        "Machine learning algorithms",
        "Manufacturing systems",
        "Steiner Tree",
        "semantic segmentation",
        "Central Processing Unit",
        "Mutual information",
        "prioritization",
        "Video sequences",
        "Gain measurement",
        "YouTube",
        "Magnetic Signature",
        "Differential-Privacy",
        "point cloud registration",
        "Deception detection",
        "randomized algorithms",
        "Web cryptography",
        "open source software",
        "Deep Generative Models",
        "space complexity",
        "Adaptation models",
        "UNet",
        "Conflict Detection",
        "in-scanner task performance",
        "wideband transceiver",
        "multi-user beamforming",
        "parsing",
        "SDP",
        "Dictionaries",
        "Generalizability",
        "Relays",
        "adaptive policies",
        "SGNS",
        "computer vision",
        "bipartite matching",
        "physiological features",
        "Image filtering",
        "Predictive models",
        "weal-leveling",
        "decontamination",
        "Visual systems",
        "Blood pressure",
        "Integrated optics",
        "Emotion recognition",
        "Time-domain analysis",
        "hardware generators",
        "Aggregates",
        "Nonlinear optics",
        "Robotics + Driving",
        "Mallows model",
        "worst case optimal join",
        "Organisms",
        "Resistive RAM",
        "Image Interpretation",
        "Portals",
        "Web servers",
        "Radio frequency",
        "Speculative Adders",
        "C# languages",
        "low precision",
        "Estimation",
        "Ubiquitous computing",
        "stochastic gradient descent (SGD)",
        "Program Analysis",
        "user representation",
        "Load management",
        "Image matching",
        "matrix sketching",
        "Knowledge engineering",
        "Proteins",
        "Tensors",
        "structured linear programming",
        "Sequential analysis",
        "Channel index matching",
        "IEEE Transactions on Circuits and Systems for Video Technology",
        "Adaptive optics",
        "characterization",
        "Computer hacking",
        "Diffraction",
        "Reed-muller (RM) codes",
        "Atmospheric modeling",
        "interactive surfaces",
        "consensus",
        "Neural generative models",
        "Data structures",
        "denoising",
        "Digital cameras",
        "DSL",
        "innovation",
        "Hardware",
        "3D shape completion",
        "Gyroscopes",
        "connected vehicles",
        "Heterogeneous networks",
        "password-based encryption",
        "one-time pad",
        "heterogeneous devices",
        "Database management systems",
        "Whole-body motion planning and control",
        "Factual",
        "Transient analysis",
        "Data storytelling",
        "low-rank",
        "image retrieval",
        "industrial loads",
        "Laplacian systems",
        "Image recognition and understanding (object detection",
        "Ink",
        "neural architecture search",
        "particularly emerging deep learning",
        "Visual Reasonin",
        "Optical crosstalk",
        "Synchronization",
        "Interaction Design",
        "Color",
        "Hardware security",
        "natural language processing",
        "information visualization",
        "literacy",
        "Lattice based cryptography",
        "circular fingerprints",
        "Error analysis",
        "Video: Action and event understanding",
        "intrusion detection",
        "Object tracking",
        "qubit mapping",
        "student engagement",
        "l1 track trigger",
        "HTML",
        "Cameras",
        "Apertures",
        "Information retrieval",
        "image memorability",
        "Mel frequency cepstral coefficient",
        "Computational efficiency",
        "gender discrimination",
        "Logic-bug",
        "disaster recovery",
        "Industrial control",
        "Approximate counting",
        "Context",
        "Data collection",
        "cortical thickness",
        "fine-grained adaptive voltage scaling (AVS)",
        "Speech synthesis",
        "Plug and Play",
        "Anisotropic magnetoresistance",
        "Depth from video",
        "emergency/disaster management",
        "System performance",
        "model explanation",
        "Internet of Things (IoT)",
        "pruning",
        "SRAM",
        "Controllability",
        "bioinformatics",
        "Visual-based navigation",
        "FinFETs",
        "engineering design",
        "Probabilistic logic",
        "Ocular",
        "Motion analysis",
        "motion and path planning",
        "Tabular Data",
        "low-bit training",
        "Vision and Scene Understanding",
        "Depression",
        "text analytics",
        "Vehicle dynamics",
        "Hafnium compounds",
        "optimal transport",
        "discrete distribution learning",
        "Stability",
        "Worst-case complexity",
        "Q measurement",
        "3D from a single image and shape-from-x",
        "sonification",
        "depth imaging",
        "Knowledge discovery",
        "Visual servoing",
        "Steiner Forest",
        "Interference cancellation",
        "Quantization (signal)",
        "IEEE Computer Graphics and Applications",
        "Internet Measurement",
        "Surveillance",
        "Vertex Connectivity.",
        "millimeter-wave (mm-wave)",
        "learning objectives",
        "CMOS",
        "Adhesives",
        "sensors",
        "Intelligent systems",
        "Insulation life",
        "large language models",
        "graphical models",
        "Robust training",
        "Discrete Fourier transforms",
        "Taxonomy",
        "fairness",
        "physiological parameters",
        "Multimodal sensors",
        "Ultrasonic imaging",
        "TV",
        "repository mining",
        "Aperture antennas",
        "wirelessly powered communications",
        "Shift registers",
        "Wavelet transforms",
        "Communication channels",
        "Transmitting antennas",
        "detection",
        "retrieval",
        "swarms",
        "Poles and towers",
        "Surface treatment",
        "Complementary Product Recommendations",
        "optimization",
        "hardware acceleration",
        "Approximation algorithms",
        "Dogs",
        "Pollution",
        "CMOS image sensors",
        "pad",
        "Timing",
        "Data Structures and Algorithms",
        "industrial load",
        "submodular function minimization",
        "Narration",
        "Pattern Recognition",
        "Surface reconstruction",
        "IEEE Transactions on Games",
        "Generative adversarial networks",
        "Object detection",
        "Information and communication technology",
        "game interfaces",
        "Fourier Analysis",
        "Steel",
        "Cardiac index",
        "monitoring terminal",
        "Scene understanding",
        "PCA",
        "collision avoidance",
        "Sleep",
        "Predictive control",
        "image rejection",
        "multimodal processing",
        "Manipulators",
        "Energy efficiency",
        "Autonomous agents",
        "perception for grasping and manipulation",
        "Heart",
        "Calculus",
        "Quadratic Assignment Problem",
        "Cooling",
        "Actuators",
        "transfer learning",
        "system-on-chip",
        "Image generation",
        "FPGA",
        "rapid prototyping",
        "Density functional estimation",
        "Information theory",
        "RF",
        "Recognition (Psychology)",
        "map hacks",
        "Speech translation",
        "High-dimensional Sampling",
        "Graph Matching",
        "Facebook",
        "implict mle",
        "Numerical models",
        "recognition",
        "Channel estimation",
        "Cost function",
        "Robustness",
        "Handover",
        "Spatial databases",
        "Design automation",
        "Mice",
        "Agriculture",
        "Virtual machine monitors",
        "Hamming distance",
        "Energy consumption",
        "Adversarial learning",
        "MAP inference",
        "Schalkwijk–Kailath scheme",
        "gyroscope",
        "Dairy products",
        "Multi-domain ring bus",
        "Sensor Fusion",
        "Attack Surface Minimization",
        "Battery cells and packs",
        "DenseNet",
        "Covariance matrices",
        "Bayes methods",
        "Program Synthesis",
        "Springs",
        "image and video synthesis",
        "Registers",
        "3D from single images",
        "Government"
}

# funding_post = """
# Combinatorial optimization problems are ubiquitous across various industries, ranging from logistics 
# and transportation to finance and engineering. This research project seeks to leverage the capabilities 
# of neural networks to develop novel approaches for solving these intricate problems more efficiently and 
# effectively than traditional methods. By combining the strengths of artificial intelligence and optimization, 
# we aim to push the boundaries of what's possible and create innovative solutions with real-world impact.
# """


