"""empty message

Revision ID: 1fd0ddac9e13
Revises: a5d1f2006203
Create Date: 2023-08-21 06:04:13.098285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd0ddac9e13'
down_revision = 'a5d1f2006203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_link', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_column('image_link')

    # ### end Alembic commands ###
