"""empty message

Revision ID: a5d1f2006203
Revises: 7a6beb934fff
Create Date: 2023-08-20 20:50:18.455802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d1f2006203'
down_revision = '7a6beb934fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding', schema=None) as batch_op:
        batch_op.alter_column('funding_post',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=30000),
               existing_nullable=False)
        batch_op.alter_column('requirement_description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=5000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding', schema=None) as batch_op:
        batch_op.alter_column('requirement_description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
        batch_op.alter_column('funding_post',
               existing_type=sa.String(length=30000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###
