"""empty message

Revision ID: 038a3232a8cc
Revises: 34b85f2f6e8d
Create Date: 2023-08-23 20:33:39.017376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038a3232a8cc'
down_revision = '34b85f2f6e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=500), nullable=True))
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###
