"""empty message

Revision ID: 14065191325a
Revises: 038a3232a8cc
Create Date: 2023-08-24 01:14:53.899890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14065191325a'
down_revision = '038a3232a8cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_fields',
    sa.Column('funding_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funding_id'], ['funding.id'], ),
    sa.PrimaryKeyConstraint('funding_id', 'field_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funding_fields')
    # ### end Alembic commands ###
