"""empty message

Revision ID: 4aab4b33c11f
Revises: ac4c152791c1
Create Date: 2023-08-28 13:38:14.233219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aab4b33c11f'
down_revision = 'ac4c152791c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('on_going_research', schema=None) as batch_op:
        batch_op.drop_constraint('on_going_research_funding_id_fkey', type_='foreignkey')
        batch_op.drop_column('funding_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('on_going_research', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funding_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('on_going_research_funding_id_fkey', 'funding', ['funding_id'], ['id'])

    # ### end Alembic commands ###
