"""empty message

Revision ID: 63e3c9099f69
Revises: 14065191325a
Create Date: 2023-08-25 00:35:01.908759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e3c9099f69'
down_revision = '14065191325a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university_rank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university_rank', schema=None) as batch_op:
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###
