"""empty message

Revision ID: 6da9956f7aad
Revises: a5a575fdd924
Create Date: 2023-09-09 21:56:18.960021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da9956f7aad'
down_revision = 'a5a575fdd924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university_rank', schema=None) as batch_op:
        batch_op.drop_column('area_of_interest_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university_rank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_of_interest_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
