"""empty message

Revision ID: 6e294cb684ce
Revises: 9b570dd3f186
Create Date: 2023-09-10 03:09:14.271270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e294cb684ce'
down_revision = '9b570dd3f186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.alter_column('abstract',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.String(length=20000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.alter_column('abstract',
               existing_type=sa.String(length=20000),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)

    # ### end Alembic commands ###
