"""empty message

Revision ID: 7a6beb934fff
Revises: 2cbbdab710fb
Create Date: 2023-08-20 20:40:50.090404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6beb934fff'
down_revision = '2cbbdab710fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor_publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'professor', ['professor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor_publication', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('professor_id')

    # ### end Alembic commands ###
