"""empty message

Revision ID: 82edeb3ce8f7
Revises: b98182940fac
Create Date: 2023-08-18 19:22:49.459207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82edeb3ce8f7'
down_revision = 'b98182940fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('research_area', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('research_area')
        batch_op.drop_column('keywords')

    # ### end Alembic commands ###
