"""empty message

Revision ID: 998a9adc72af
Revises: 4aab4b33c11f
Create Date: 2023-08-28 14:23:35.628675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998a9adc72af'
down_revision = '4aab4b33c11f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('on_going_research', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funding_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'funding', ['funding_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('on_going_research', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('funding_id')

    # ### end Alembic commands ###
