"""empty message

Revision ID: 9b570dd3f186
Revises: 6da9956f7aad
Create Date: 2023-09-10 02:20:03.478687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b570dd3f186'
down_revision = '6da9956f7aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.alter_column('doi',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.drop_constraint('publication_doi_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.create_unique_constraint('publication_doi_key', ['doi'])
        batch_op.alter_column('doi',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
