"""empty message

Revision ID: a5a575fdd924
Revises: 
Create Date: 2023-09-09 21:50:52.170392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a575fdd924'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professor_website_link')
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_column('website_link')

    op.create_table('professor_website_link',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('professor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('website_link', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('website_type', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], name='professor_website_link_professor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='professor_website_link_pkey')
    )
    # ### end Alembic commands ###
