"""empty message

Revision ID: c727d0568881
Revises: 82edeb3ce8f7
Create Date: 2023-08-20 15:55:38.195694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c727d0568881'
down_revision = '82edeb3ce8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor_publication', schema=None) as batch_op:
        batch_op.drop_column('number_of_citations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor_publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_citations', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
