"""empty message

Revision ID: ca5f1cc79e63
Revises: 6e294cb684ce
Create Date: 2023-09-10 17:22:18.039276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5f1cc79e63'
down_revision = '6e294cb684ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_area_of_interest',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('area_of_interest_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('student_id', 'area_of_interest_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_area_of_interest')
    # ### end Alembic commands ###
